# python/realtime/run_realtime.py
"""
Runner for Meridian v0.2.

This file is intentionally runnable as:
  python python/realtime/run_realtime.py
from repository root.

It patches sys.path so imports work without packaging steps.
"""

import os
import sys
import csv

# Add repo_root/python to sys.path
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PY_ROOT = os.path.join(REPO_ROOT, "python")
if PY_ROOT not in sys.path:
    sys.path.insert(0, PY_ROOT)

from config import LOG_CSV_PATH, V0_2_REQUIRED_COLUMNS  # noqa: E402
from realtime.meridian_realtime_agent import RealTimeMeridianAgent  # noqa: E402


def validate_existing_log_header(log_path):
    """
    Validate that existing log file has v0.2 required columns in header.

    Returns:
        (ok: bool, missing: list) - ok=True if all required columns present,
                                     missing=list of missing column names
    """
    if not os.path.exists(log_path):
        return (True, [])  # No existing log, OK to proceed

    try:
        with open(log_path, 'r') as f:
            reader = csv.reader(f)
            header = next(reader, None)

            if header is None:
                return (False, V0_2_REQUIRED_COLUMNS)  # Empty file, all missing

            missing = [col for col in V0_2_REQUIRED_COLUMNS if col not in header]
            return (len(missing) == 0, missing)

    except Exception:
        # If we can't read the file, assume it's invalid
        return (False, V0_2_REQUIRED_COLUMNS)


if __name__ == "__main__":
    # PR13B: Guard against pre-v0.2 log files (fail-fast)
    log_path = os.path.join(REPO_ROOT, LOG_CSV_PATH)
    ok, missing = validate_existing_log_header(log_path)

    if not ok:
        print("=" * 70)
        print("ERROR: Existing log file is incompatible with v0.2")
        print("=" * 70)
        print(f"Log file: {log_path}")
        print(f"Missing required columns: {', '.join(missing)}")
        print("")
        print("This log was likely generated by a pre-v0.2 agent.")
        print("")
        print("Action required:")
        print(f"  1. Delete the old log: rm {log_path}")
        print(f"  2. Or rename it: mv {log_path} {log_path}.old")
        print("")
        print("Then re-run this command.")
        print("=" * 70)
        sys.exit(1)

    RealTimeMeridianAgent().run()
